package project;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import project.connect;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class BAdd extends javax.swing.JFrame {

    /**
     * Creates new form BAdd
     */
    public BAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bw_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bw_address = new javax.swing.JTextField();
        bw_amount = new javax.swing.JTextField();
        bw_email = new javax.swing.JTextField();
        bw_id = new javax.swing.JTextField();
        bw_contact = new javax.swing.JTextField();
        bw_borrowed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setText("Borrower Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 242, 180, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setText("Borrower Contact");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 292, 180, -1));

        bw_name.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_nameActionPerformed(evt);
            }
        });
        getContentPane().add(bw_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 142, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setText("Book Borrowed");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, -1));

        bw_address.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_addressActionPerformed(evt);
            }
        });
        getContentPane().add(bw_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 192, 160, -1));

        bw_amount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_amountActionPerformed(evt);
            }
        });
        getContentPane().add(bw_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 392, 160, 30));

        bw_email.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_emailActionPerformed(evt);
            }
        });
        getContentPane().add(bw_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 242, 160, 30));

        bw_id.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_idActionPerformed(evt);
            }
        });
        getContentPane().add(bw_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 89, 160, 30));

        bw_contact.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_contactActionPerformed(evt);
            }
        });
        getContentPane().add(bw_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 292, 160, 30));

        bw_borrowed.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_borrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bw_borrowedActionPerformed(evt);
            }
        });
        getContentPane().add(bw_borrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Fine Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("Borrower Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 89, 120, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("Borrower Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 142, 180, -1));

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Book21.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 140, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("Borrower Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 192, -1, -1));

        jButton3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Book22.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 170, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG3.jpeg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bw_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_nameActionPerformed

    private void bw_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_addressActionPerformed

    private void bw_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_amountActionPerformed

    private void bw_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_emailActionPerformed

    private void bw_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_idActionPerformed

    private void bw_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_contactActionPerformed

    private void bw_borrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bw_borrowedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bw_borrowedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(bw_id.getText().equals("")||bw_name.getText().equals("")||bw_address.getText().equals("")||bw_email.getText().equals("")||bw_contact.getText().equals("")||bw_contact.getText().equals("") || bw_email.getText().equals("")||bw_contact.getText().equals("")||bw_borrowed.getText().equals("") || bw_email.getText().equals("")||bw_contact.getText().equals("")||bw_amount.getText().equals("") )
      {
          JOptionPane.showMessageDialog(this,"Please fill all the details !!","Error",JOptionPane.WARNING_MESSAGE);
      }
      else if(bw_id.getText().length() <= 0)
      {
        JOptionPane.showMessageDialog(this,"Invalid Borrower Id","Error",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
          String Id = bw_id.getText();
          String Name = bw_name.getText();
          String Address = bw_address.getText();
          String Email = bw_email.getText();
          String Contact = bw_contact.getText();
          String Borrowed = bw_borrowed.getText();
          String Amount = bw_amount.getText();
          //performing the DB connection for inserting into DB
          try
          {
           Connection con = connect.dbconnection();
           Statement st = con.createStatement();
           String sql = "insert into borrowers(BOR_ID,BOR_NAME,BOR_ADDRESS,BOR_EMAIL,BOR_CONTACT,BK_BORROWED,FINE_AMT) values('"+Id+"','"+Name+"','"+Address+"','"+Email+"','"+Contact+"','"+Borrowed+"','"+Amount+"')";
           st.executeUpdate(sql);
           JOptionPane.showMessageDialog(this,"Borrower Added successfully !!");
           bw_id.setText("");
           bw_name.setText("");
           bw_address.setText("");
           bw_email.setText("");
           bw_contact.setText("");
           bw_borrowed.setText("");
           bw_amount.setText("");
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(this,"Database Connection Failed !!","ERROR",JOptionPane.ERROR_MESSAGE);
              System.out.println(e);
          }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BAdd j1 = new BAdd();
                ImageIcon img = new ImageIcon(getClass().getResource("/Images/Borrow1.png"));
                j1.setIconImage(img.getImage());
                j1.setTitle("Add Borrower");
                j1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bw_address;
    private javax.swing.JTextField bw_amount;
    private javax.swing.JTextField bw_borrowed;
    private javax.swing.JTextField bw_contact;
    private javax.swing.JTextField bw_email;
    private javax.swing.JTextField bw_id;
    private javax.swing.JTextField bw_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
