/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Neha Deshpande
 */
public class BUpdate extends javax.swing.JFrame {

    /**
     * Creates new form BUpdate
     */
    public BUpdate() {
        initComponents();
        
        //setting label to invisible
        name.setVisible(false);
        address.setVisible(false);
        email.setVisible(false);
        contact.setVisible(false);
        borrowed.setVisible(false);
        fine.setVisible(false);
        //setting textfield to invisible
        bname.setVisible(false);
        baddress.setVisible(false);
        bemail.setVisible(false);
        bcontact.setVisible(false);
        bborrowed.setVisible(false);
        bfine.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        fine = new javax.swing.JLabel();
        borrowed = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        baddress = new javax.swing.JTextField();
        bemail = new javax.swing.JTextField();
        bcontact = new javax.swing.JTextField();
        bborrowed = new javax.swing.JTextField();
        bfine = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        bfetch = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        name.setText("Borrower Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 121, 163, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Borrower Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 134, -1));

        address.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        address.setText("Borrower Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 176, -1, -1));

        contact.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        contact.setText("Borrower Contact");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 277, 193, -1));

        email.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        email.setText("Borrower Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 229, 172, -1));

        fine.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        fine.setText("Fine Amount");
        getContentPane().add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 373, 159, -1));

        borrowed.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        borrowed.setText("Book Borrowed");
        getContentPane().add(borrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 325, 167, -1));

        bid.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 79, 203, -1));

        bname.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 121, 203, -1));

        baddress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(baddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 176, 203, -1));

        bemail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(bemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 229, 203, -1));

        bcontact.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(bcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 277, 203, -1));

        bborrowed.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bborrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bborrowedActionPerformed(evt);
            }
        });
        getContentPane().add(bborrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 325, 203, -1));

        bfine.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfineActionPerformed(evt);
            }
        });
        getContentPane().add(bfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 373, 203, -1));

        Update.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Book23.png"))); // NOI18N
        Update.setText("Update");
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 200, -1));

        bfetch.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        bfetch.setForeground(new java.awt.Color(255, 0, 0));
        bfetch.setText("Fetch");
        bfetch.setBorder(null);
        bfetch.setBorderPainted(false);
        bfetch.setContentAreaFilled(false);
        bfetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfetchActionPerformed(evt);
            }
        });
        getContentPane().add(bfetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 135, 57));

        bclose.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        bclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Book22.png"))); // NOI18N
        bclose.setText("Close");
        bclose.setBorder(null);
        bclose.setBorderPainted(false);
        bclose.setContentAreaFilled(false);
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });
        getContentPane().add(bclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 135, 57));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG7.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void bborrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bborrowedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bborrowedActionPerformed

    private void bfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bfineActionPerformed

    private void bfetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfetchActionPerformed
        //fetch button action 
        if(bid.getText().equals(""))
        {
          JOptionPane.showMessageDialog(this,"Please enter borrower id !","Error ",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        try
        {
         String Id = bid.getText();
         Connection con = connect.dbconnection();
         Statement st = con.createStatement();
         String sql = "select * from Borrowers where BOR_ID ='"+Id+"'";
         ResultSet rs = st.executeQuery(sql);
         if(rs.next())
         {
           //extracting data from result set
           String Name = rs.getString("BOR_NAME");
           String Address = rs.getString("BOR_ADDRESS");
           String Email = rs.getString("BOR_EMAIL");
           String Contact = rs.getString("BOR_CONTACT");
           String Borrowed = rs.getString("BK_BORROWED");
           String Fine = rs.getString("FINE_AMT");
           //setting data to corresponding field
           bname.setText(Name);
           baddress.setText(Address);
           bemail.setText(Email);
           bcontact.setText(Contact);
           bborrowed.setText(Borrowed);
           bfine.setText(Fine);
           
           //setting label to visible
           name.setVisible(true);
           address.setVisible(true);
           email.setVisible(true);
           contact.setVisible(true);
           borrowed.setVisible(true);
           fine.setVisible(true);
           //setting textfield to visible
           bname.setVisible(true);
           baddress.setVisible(true);
           bemail.setVisible(true);
           bcontact.setVisible(true);
           bborrowed.setVisible(true);
           bfine.setVisible(true);
         }
         else
         {
             JOptionPane.showMessageDialog(this,"Invalid Borrower Id","Error",JOptionPane.ERROR_MESSAGE);
             bid.setText("");
         }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Database Connection Failed !!","ERROR",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
        
        }     
    }//GEN-LAST:event_bfetchActionPerformed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bcloseActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
                                          
        //update button action
        try
        {
           //fetching user enter data
           String id = bid.getText();
           String name = bname.getText();
           String address = baddress.getText();
           String email = bemail.getText();
           String contact = bcontact.getText();
           String borrow = bborrowed.getText();
           String fine = bfine.getText();
           //establishing connection
           Connection con = connect.dbconnection();
           Statement st = con.createStatement();
           String sql = "update borrowers set BOR_NAME ='"+name+"',BOR_ADDRESS = '"+address+"',BOR_EMAIL = '"+email+"',BOR_CONTACT = '"+contact+"',BK_BORROWED = '"+borrow+"',FINE_AMT= '"+fine+"' where BOR_ID = '"+id+"'";
           st.executeUpdate(sql);
           JOptionPane.showMessageDialog(this,"Borrower Details updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE); 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Database Connection Failed !!","ERROR",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BUpdate j = new BUpdate();
                ImageIcon img = new ImageIcon(getClass().getResource("/Images/borrow2.png"));
                j.setIconImage(img.getImage());
                j.setTitle("Update Book");
                j.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JLabel address;
    private javax.swing.JTextField baddress;
    private javax.swing.JTextField bborrowed;
    private javax.swing.JButton bclose;
    private javax.swing.JTextField bcontact;
    private javax.swing.JTextField bemail;
    private javax.swing.JButton bfetch;
    private javax.swing.JTextField bfine;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bname;
    private javax.swing.JLabel borrowed;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fine;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
